hotfeature/8440 - add new route for change password page
theticketfairy/tf-checkout-react pull request #146
Opened 2022-01-17 10:15 UTC by ft-tiny

2022-01-17 11:28 UTC, ft-worker requested changes

2022-01-17 11:28 UTC, ft-worker commented on src/api/index.ts
> +export const resetPassword = (data: any) => publicRequest.post(`/v1/oauth/reset-password-rn`, data)
Please add data type.

2022-01-17 11:28 UTC, ft-worker commented on example/Routes.tsx
> +        tokenProps=''
Rename `tokenProps`. It's `token` property getting from props.

2022-01-17 11:28 UTC, ft-worker commented on src/components/resetPasswordContainer/index.tsx
> +                    <TextField
Use `CustomField` component.

2022-01-17 11:28 UTC, ft-worker commented on src/components/resetPasswordContainer/index.tsx
> +                    <TextField
Use `CustomField` component.

2022-01-17 11:28 UTC, ft-worker commented on src/components/resetPasswordContainer/index.tsx
> +interface Props {
Please prefix interface with `I` and rename it: `IResetPasswordProps` or `IResetPasswordContainerProps`.

2022-01-17 11:28 UTC, ft-worker commented on src/components/resetPasswordContainer/index.tsx
> +            if (axios.isAxiosError(e)) onResetPasswordError(e)
Add `if` condition's body brackets.

2022-01-17 11:29 UTC, ft-worker commented
@ft-tiny add task's description and number in PR's description.

2022-01-17 13:53 UTC, ft-tiny commented on src/api/index.ts
> +export const resetPassword = (data: any) => publicRequest.post(`/v1/oauth/reset-password-rn`, data)
done

2022-01-17 13:53 UTC, ft-tiny commented on example/Routes.tsx
> +        tokenProps=''
done

2022-01-17 13:53 UTC, ft-tiny commented on src/components/resetPasswordContainer/index.tsx
> +                    <TextField
done

2022-01-17 13:53 UTC, ft-tiny commented on src/components/resetPasswordContainer/index.tsx
> +                    <TextField
done

2022-01-17 13:54 UTC, ft-tiny commented on src/components/resetPasswordContainer/index.tsx
> +interface Props {
done

2022-01-17 13:54 UTC, ft-tiny commented on src/components/resetPasswordContainer/index.tsx
> +            if (axios.isAxiosError(e)) onResetPasswordError(e)
done

2022-01-17 18:47 UTC, ft-worker commented on src/components/resetPasswordContainer/index.tsx
> +                <Field
Field type must be `password`.

2022-01-17 18:48 UTC, ft-worker commented on src/components/resetPasswordContainer/index.tsx
> +                <Field
Field type must be `password`.

2022-01-18 12:01 UTC, ft-tiny commented on src/components/resetPasswordContainer/index.tsx
> +                <Field
done

2022-01-19 07:32 UTC, ft-worker approved these changes

2022-01-19 13:30 UTC, merged