Hotfeature/8558 - Access code improvement
theticketfairy/tf-checkout-react pull request #151
Opened 2022-02-09 06:02 UTC by ft-lucky

When the user applies the Access code
Then "PROMO CODE APPLIED SUCCESSFULLY" message is displayed
Please also display the "Got a promo code? Click here" message with the possibility to input a new access code.

2022-02-11 13:15 UTC, ft-worker requested changes

2022-02-11 13:15 UTC, ft-worker commented on src/components/ticketsContainer/PromoCodeSection.tsx
> +      {(showPromoInput || (!isPromotionsEnabled && !showPromoInput && isAccessCodeEnabled && !promoCodeIsApplied)) && (
Need to simplify checkings.

2022-02-15 18:01 UTC, r9software requested changes

2022-02-15 18:01 UTC, r9software commented on src/components/ticketsContainer/PromoCodeSection.tsx
> +      {(showPromoInput || (!isPromotionsEnabled && !showPromoInput && isAccessCodeEnabled && !promoCodeIsApplied)) && (
this can't be merged without simply checkings and review that the use cases of HOX are still covered

2022-02-23 09:57 UTC, ft-lucky commented
RN connected PR - https://github.com/restlessnites/rn-site/pull/160

2022-02-25 07:02 UTC, ft-worker approved these changes

2022-02-25 10:14 UTC, merged