9345 - add field level validation for phone number
theticketfairy/tf-checkout-react pull request #198
Opened 2022-06-07 15:17 UTC by ft-tiny

A validation for phone numbers during a checkout flow is needed for checkout flow.
Details on E164 - https://www.twilio.com/docs/glossary/what-e164

2022-06-10 07:11 UTC, ft-tiny commented on src/components/billing-info-container/index.tsx
> +                                      element.type === 'holderPhone' ?
done

2022-06-20 08:14 UTC, ft-lucky requested changes

2022-06-20 08:14 UTC, ft-lucky commented on src/components/common/PhoneNumberField.tsx
> +export interface ISelectOption {
Please remove unnecessary interface

2022-06-20 08:17 UTC, ft-tiny commented on src/components/common/PhoneNumberField.tsx
> +export interface ISelectOption {
done

2022-07-20 11:16 UTC, ft-worker approved these changes

2022-07-21 08:06 UTC, closed without merging