#8472 - Checkout package changes for rn
theticketfairy/tf-checkout-react pull request #92
Opened 2021-12-08 06:21 UTC by ft-lucky

2021-12-08 08:07 UTC, ft-worker requested changes

2021-12-08 08:07 UTC, ft-worker commented on src/components/paymentContainer/index.tsx
> +  disableZipSection,
Add default value.

2021-12-08 08:07 UTC, ft-worker commented on src/components/billing-info-container/index.tsx
> +                  <div>{accountInfoTitle}</div>
Make corresponding changes for HOX.

2021-12-08 08:07 UTC, ft-worker commented on src/components/billing-info-container/index.tsx
> +  accountInfoTitle: any;
Add type(s).

2021-12-08 08:07 UTC, ft-worker commented on src/api/index.ts
> +  ttfHeaders['X-Source-Origin'] = 'restlessnit.es'
Set `X-Source-Origin` from props in `setConfigs` function call.

2021-12-08 08:07 UTC, ft-worker commented on src/api/index.ts
> +  // 'http://localhost',
Remove `discardedOrigins` and connected functionality.

2021-12-08 11:07 UTC, ft-lucky commented on src/components/billing-info-container/index.tsx
> +                  <div>{accountInfoTitle}</div>
PR for HOX - https://github.com/HouseOfXNYC/houseofxsite/pull/119

2021-12-08 13:41 UTC, ft-worker requested changes

2021-12-08 13:41 UTC, ft-worker commented on src/components/confirmationContainer/index.tsx
>          const dataDecoded = JSON.parse(dataEncoded)
`const dataDecoded = dataEncoded ? JSON.parse(dataEncoded) : { hash: orderHash }`

2021-12-09 07:56 UTC, ft-worker approved these changes

2021-12-09 07:56 UTC, merged