Hotfix/8385 waiting list style changes
theticketfairy/tf-checkout-react pull request #98
Opened 2021-12-09 14:26 UTC by ft-lucky

2021-12-09 15:34 UTC, ft-worker requested changes

2021-12-09 15:34 UTC, ft-worker commented on src/components/waitingList/index.tsx
> +      {!showSuccessMessage ? (
Wrong condition

2021-12-10 06:15 UTC, ft-lucky commented on src/components/waitingList/index.tsx
> +      {!showSuccessMessage ? (
done

2021-12-10 07:07 UTC, ft-worker approved these changes

2021-12-10 07:07 UTC, merged